ALTER TABLE coach MODIFY COLUMN intro TEXT;
ALTER TABLE coach ADD COLUMN avatar_url VARCHAR(512);
ALTER TABLE coach ADD COLUMN photo_url VARCHAR(512);
ALTER TABLE coach ADD COLUMN specialty VARCHAR(200);
ALTER TABLE coach ADD COLUMN rating DECIMAL(3,1) DEFAULT 5.0;
ALTER TABLE coach ADD COLUMN lesson_taught INT NOT NULL DEFAULT 0;
ALTER TABLE coach ADD COLUMN certificate_urls TEXT;

ALTER TABLE course_pack MODIFY COLUMN content TEXT;
ALTER TABLE course_pack MODIFY COLUMN audience TEXT;
ALTER TABLE course_pack ADD COLUMN cover_url VARCHAR(512);
ALTER TABLE course_pack ADD COLUMN minutes_per_lesson INT NOT NULL DEFAULT 60;
